model_trainer:
  epochs: 1
  output_dir : 'pegasus-samsum'        
  num_train_epochs : 1                
  per_device_train_batch_size : 1 
  per_device_eval_batch_size : 1  
  warmup_steps : 500              
  gradient_accumulation_steps : 8 
  weight_decay : 0.01 




